# Generated by Django 5.0.6 on 2024-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_signup_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email_address',
            field=models.CharField(default='A', max_length=40),
        ),
    ]
