# Generated by Django 5.0.6 on 2024-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_signup_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password1',
            field=models.CharField(default='A', max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password2',
            field=models.CharField(default='A', max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password3',
            field=models.CharField(default='A', max_length=255),
        ),
    ]
