# Generated by Django 5.0.6 on 2024-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_signup_password1_alter_signup_password2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='A', max_length=30)),
                ('Date', models.CharField(default='A', max_length=12)),
                ('Time', models.CharField(default='A', max_length=16)),
                ('Status', models.CharField(default='A', max_length=16)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
